networks:
  smakolyk:
    driver: bridge

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smakolyk

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - smakolyk

  web:
    build: .
    restart: always
    volumes:
      - .:/app
      - static_volume:/app/static/
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    networks:
      - smakolyk

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - smakolyk

  celery_beat:
    build: .
    command: celery -A core beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    networks:
      - smakolyk

  nginx:
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - ./nginx/:/etc/nginx/conf.d/
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    depends_on:
      - web
    networks:
      - smakolyk

volumes:
  postgres_data:
  static_volume:
  redis_data:
