# Generated by Django 4.2.6 on 2024-04-16 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_course", models.CharField(max_length=100, unique=True)),
                ("first_course_price", models.PositiveIntegerField()),
                ("second_course", models.CharField(max_length=100, unique=True)),
                ("second_course_price", models.PositiveIntegerField()),
                ("dessert", models.CharField(max_length=100, unique=True)),
                ("dessert_price", models.PositiveIntegerField()),
                ("drink", models.CharField(max_length=100, unique=True)),
                ("drink_price", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("first_course", models.CharField(blank=True, max_length=30)),
                ("first_course_quantity", models.PositiveIntegerField(default=0)),
                ("second_course", models.CharField(blank=True, max_length=30)),
                (
                    "second_course_quantity",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                ("dessert", models.CharField(blank=True, max_length=30)),
                (
                    "dessert_quantity",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                ("drink", models.CharField(blank=True, max_length=30)),
                ("drink_quantity", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("first_course", models.CharField(blank=True, max_length=100)),
                ("first_course_quantity", models.PositiveIntegerField(default=0)),
                ("second_course", models.CharField(blank=True, max_length=100)),
                ("second_course_quantity", models.PositiveIntegerField(default=0)),
                ("dessert", models.CharField(blank=True, max_length=100)),
                ("dessert_quantity", models.PositiveIntegerField(default=0)),
                ("drink", models.CharField(blank=True, max_length=100)),
                ("drink_quantity", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
